
# Netlify configuration file
[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Redirect all API requests to Netlify functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Redirect everything else to index.html (for SPA routing)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
